import LeftBar from "@/components/sidebars/LeftBar";
import { Inter } from "next/font/google";
import "../globals.css";
import RightBar from "@/components/sidebars/RightBar";
import ThemeProvider from "../theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Infinity",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-background">
      <body className={inter.className}>
        <div className="p-4 mr-2 lg:ml-64 lg:mr-72 mb-10">
          <ThemeProvider>
            <LeftBar />
            <RightBar />
            {children}
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
